id: AD5FDCF6D
title: 'Swift Bestowal of Blessings: A Sādhana of Peaceful Mañjuśrī'
type: translation
pechas:
- I699D65D6
- I4A3A7BAF
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:50:22.593212
  last_modified_at: 2023-01-04 12:50:22.593232
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I699D65D6/7C0F: 2D20
  I4A3A7BAF/6383: 2D20
